function HangingGardenofBabylon(){
   window.alert("The Hanging Gardens of Babylon were one of the Seven Wonders of the Ancient World listed by Hellenic culture.");
}
function TajMahal(){
    window.alert("The Taj Mahal, is an ivory-white marble mausoleum on the southern bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself");
 }
 function Giza(){
    window.alert("The Great Pyramid of Giza is the oldest and largest of the pyramids in the Giza pyramid complex bordering present-day Giza in Greater Cairo, Egypt. It is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact.");
 }
 function Zeus(){
    window.alert("The Statue of Zeus at Olympia was a giant seated figure, about 12.4 m tall, made by the Greek sculptor Phidias around 435 BC at the sanctuary of Olympia, Greece, and erected in the Temple of Zeus there. Zeus is the sky and thunder god in ancient Greek religion, who rules as king of the gods of Mount Olympus.");
 }